version: '3.10'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: example  # Здесь необходимо заменить на свои данные
      POSTGRES_PASSWORD: example  # Здесь необходимо заменить на свои данные
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: